CompileFlags:                     # Tweak the parse settings
  Add: [-xc++, -Wall,-I,"/usr/include/c++/11",-I,"/usr/include/x86_64-linux-gnu/c++/11/"]             # treat all files as C++, enable more warnings
  Remove: -W*                     # strip all other warning-related flags
  
If:
  PathExclude: ~/Mbed Programs/*
